[phases.setup]
# Usa Bun como runtime y gestor de paquetes
nixPkgs = ["bun", "git"]

[phases.build]
cmds = [
  "bun install",
  "bun run build",
  "bun run migrate",
]

[phases.start]
cmd = "bun run start"
