providers = ["bun"]

[phases.setup]
nixPkgs = ["bun", "mysql", "openssl", "glibc"]

[phases.install]
cmds = ["bun i --no-save"]

[phases.build]
cmds = [
  "bun install",
  "bun run build"
]

[start]
cmd = "bun run start"